apiVersion: v1
kind: Pod 
metadata:
  name: antiaffinity-demo
  labels:
    purpose: nodeaffinity
    project: roboshop
spec:
  
  affinity:
    nodeAffinity:
      # hard rule
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: NotIn
            values:
            - us-east-1f

  containers:
  - name: nginx
    image: nginx:latest
    imagePullPolicy: Always